# Generated by Django 5.2.5 on 2026-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('box', 'Box'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('meter', 'Meter'), ('carton', 'Carton'), ('bag', 'Bag')], default='piece', max_length=20),
        ),
    ]
