# Generated by Django 5.2.5 on 2026-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
